spring:
  datasource:
    url: jdbc:mysql://ubuntu:3306/web_beneficios
    username: root
    password: Prueba$1
  mvc:
    favicon:
      enabled: true
    

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImproveNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect